### ISSUE TITLE
funcとmcpもパッケージ管理はuvにする

### ISSUE THREAD

**Issue by Tomodo1773** [Tomodo1773/line-character-agent#95]

**Comment by Tomodo1773** [comment]
src/func,src/mcpはpoetryでパッケージ管理しているが、uvで管理するように変える。
また、デプロイにはrequirements.txtが必要であるため、src/apiがやっているように、pipelineでデプロイ前にrequirements.txtを生成する。
@claude
コメントは日本語でして

**Comment by Tomodo1773** [comment]
@claude
pre-commitでruffでlint,formatをするように設定欲しいです。
pre-commitの設定はリポジトリ全体で1つです。以下を参考にして
```
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.3
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
```

line-lengthは127にして
